# Generated by Django 6.0.3 on 2026-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="date_ended",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="journal",
            name="map_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journal",
            name="player1_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="journal",
            name="player2_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
