# Generated by Django 6.0.3 on 2026-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_journal_date_ended_journal_map_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journal",
            name="map_image",
            field=models.TextField(blank=True),
        ),
    ]
