# Generated by Django 6.0.3 on 2026-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_entry_edited_at_journal_map_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="map_image_left",
            field=models.TextField(blank=True),
        ),
    ]
